# Generated by Django 5.2.8 on 2025-11-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
