# Generated by Django 5.2.4 on 2025-08-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_number_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='trial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
