# Generated by Django 5.2.4 on 2025-08-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_trial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trial',
        ),
    ]
