# Generated by Django 5.2.4 on 2025-08-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_delete_trial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Booking2',
        ),
    ]
