# Generated by Django 5.2.4 on 2025-08-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_booking2_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menu2',
        ),
    ]
