# Generated by Django 5.2.4 on 2025-08-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_rename_menu_menu2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu2',
            new_name='Menu',
        ),
    ]
