# Generated by Django 5.2.4 on 2025-07-29 06:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart',
            new_name='Cart',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
